# Generated by Django 5.1 on 2024-09-08 09:44

import django.db.models.deletion
import ebook_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('authors_id', models.AutoField(primary_key=True, serialize=False)),
                ('authors_first_name', models.CharField(max_length=800)),
                ('authors_middle_name', models.CharField(blank=True, max_length=800, null=True)),
                ('authors_last_name', models.CharField(max_length=800)),
                ('authors_full_name', models.CharField(max_length=800)),
                ('authors_slug', models.SlugField()),
            ],
            options={
                'db_table': 'authors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostumUsers',
            fields=[
                ('costum_users_id', models.AutoField(primary_key=True, serialize=False)),
                ('costum_users_name', models.CharField(max_length=800, unique=True)),
                ('costum_users_email', models.CharField(max_length=800, unique=True)),
                ('costum_users_password', models.CharField(max_length=800)),
                ('costum_users_password2', models.CharField(max_length=800)),
            ],
            options={
                'db_table': 'costum_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genres_id', models.AutoField(primary_key=True, serialize=False)),
                ('genres_name', models.CharField(max_length=800)),
                ('genres_slug', models.SlugField()),
            ],
            options={
                'db_table': 'genres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('publishers_id', models.AutoField(primary_key=True, serialize=False)),
                ('publishers_name', models.CharField(max_length=800)),
                ('publishers_slug', models.SlugField()),
            ],
            options={
                'db_table': 'publishers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('books_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_books', models.CharField(max_length=800)),
                ('description_books', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('link_to_file', models.FileField(blank=True, max_length=900, null=True, upload_to=ebook_api.models.book_path_local)),
                ('cover_image_path', models.FileField(blank=True, max_length=900, null=True, upload_to=ebook_api.models.book_path_local)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('book_slug', models.SlugField()),
                ('author_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_books', to='ebook_api.authors')),
                ('genre_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre_books', to='ebook_api.genres')),
                ('publisher_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher_books', to='ebook_api.publishers')),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ebook_api.books')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ebook_api.costumusers')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('what_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_rate', to='ebook_api.books')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
    ]
