# Generated by Django 5.1 on 2024-09-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image_path',
            field=models.FileField(blank=True, max_length=900, null=True, upload_to='covers_books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='link_to_file',
            field=models.FileField(blank=True, max_length=900, null=True, upload_to='books/'),
        ),
    ]
