# Generated by Django 5.1 on 2024-09-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_api', '0002_alter_books_cover_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book', to='ebook_api.books')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='ebook_api.costumusers')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
                'unique_together': {('user', 'book')},
            },
        ),
    ]
