# Generated by Django 5.1 on 2024-09-06 13:38

import ebook_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_api', '0003_remove_books_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image_path',
            field=models.FileField(blank=True, max_length=900, null=True, upload_to=ebook_api.models.book_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='books',
            name='link_to_file',
            field=models.FileField(blank=True, max_length=900, null=True, upload_to=ebook_api.models.author_directory_path),
        ),
    ]
