# Generated by Django 5.1 on 2024-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_api', '0003_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
