# Generated by Django 5.1 on 2024-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_api', '0006_alter_rating_unique_together_books_description_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
